package me.greggkr.bdb.logging

enum class LogType {
    /* Message */
    GUILD_MESSAGE_EDIT,
    GUILD_MESSAGE_DELETE,

    /* GUILD */
    GUILD_UPDATE,
    /* Member */
    GUILD_MEMBER_JOIN,
    GUILD_MEMBER_LEAVE,
    GUILD_MEMBER_NICK_CHANGE,
    GUILD_MEMBER_ROLE_ADD,
    GUILD_MEMBER_ROLE_REMOVE,
    /* Category */
    GUILD_CATEGORY_CREATE,
    GUILD_CATEGORY_DELETE,
    /* Text Channel */
    GUILD_TEXTCHANNEL_CREATE,
    GUILD_TEXTCHANNEL_DELETE,
    GUILD_TEXTCHANNEL_UPDATE,
    /* Voice Channel */
    GUILD_VOICECHANNEL_CREATE,
    GUILD_VOICECHANNEL_DELETE,
    GUILD_VOICECHANNEL_UPDATE
    /* END GUILD */
}